taxi_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      port: 5432
      user: "{{ env_var('WAREHOUSE_USER', 'dataeng') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD', 'dataeng123') }}"
      dbname: taxi_warehouse
      schema: staging
      threads: 4

